// FIREBASE CONFIGURATION
// ⚠️ REEMPLAZA ESTOS VALORES CON TUS PROPIAS CREDENCIALES
// Sigue las instrucciones en FIREBASE_SETUP.md

const firebaseConfig = {
    apiKey: "REEMPLAZA_CON_TU_API_KEY",
    projectId: "REEMPLAZA_CON_TU_PROJECT_ID",
    storageBucket: "REEMPLAZA_CON_TU_STORAGE_BUCKET",
    messagingSenderId: "REEMPLAZA_CON_TU_MESSAGING_SENDER_ID",
    appId: "REEMPLAZA_CON_TU_APP_ID"
};
